---
title: "Course Assignment"
author: "Moritz Körber"
date: "15 Juli 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r message=FALSE, warning=FALSE}
# Load packages and data:
library(dplyr)
library(ggplot2)
library(caret)
library(rlist)
df <- read.csv("pml-training.csv",na.strings = c("NA","NaN","","#DIV/0!"))
set.seed(31)
```

# 1. Inspect target variable
First, I am looking at the target variable "classe":
```{r echo=FALSE}
# What is "classe"?
glimpse(df$classe)
```

Since it is a categorical variable, it is a classification problem. Hence, an algorithm like logistic regression, random forests, or knn is suitable. 

# 2. Inspect predictors
Crop predictors without any information:
```{r crop predictors without any information, echo=T}
l <- list()
for (i in 1:dim(df)[2]){
  if (any(!is.na(df[,i]))==F){
    l <- list.append(l,colnames(df)[i])
  }
}
df[unlist(l)] <- NULL
```
Check for constant predictors:


Show predictors with much information:
```{r Show predictors with much information}
l <- list()
for (i in 1:dim(df)[2]){
  if ((sum(is.na(df[,i]))/dim(df)[1])>0.9){
    l <- list.append(l,colnames(df)[i])
  }
}

df[(unlist(l))] <- NULL
```